services:
  blog:
    build: ./docker/httpd
    expose:
      - 80
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 60M
            # pids: 100
        reservations:
          cpus: '0.01'
          memory: 6M
      mode: replicated
      replicas: 1

    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80

  load_balancer:
    image: nginxproxy/nginx-proxy
    depends_on:
      - blog
    links:
      - blog
    ports:
      - 8949:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
