releaseName: my-release

httpd:
  enabled: true
  image: 
    repository: httpd
    tag: latest
  service:
    type: ClusterIP
    port: 80

nginx:
  enabled: true
  image: 
    repository: nginx
    tag: latest
  service:
    type: NodePort
    port: 80

mysql:
  db: "mysql"             # 지정 
  host: "db-mariadb.default.svc.cluster.local"     # FQDN 압력
  # config my.cnf https://dev.mysql.com/doc/c-api/8.0/en/mysql-options.html
  additionalConfig:
    # - connect-timeout=5
    # - debug
  pass: "abcd1234"    # 유저 만들때 준 비번 입력
  port: 3306              # db 서비스 포트 번호 kubectl get svc 하면 알 수 있음 
  protocol: ""
  user: "exporter"     # db user 테이블에 등록된 유저 이름 
  # secret with full config my.cnf
  existingConfigSecret:
    name: ""
    key: ""
  # secret only containing the password
  existingPasswordSecret:
    name: ""
    key: ""
